export default (app) => {
  app.post(
    `/tenant/:tenantId/document`,
    require('./documentCreate').default,
  );
  app.put(
    `/tenant/:tenantId/document/:id`,
    require('./documentUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/document/import`,
    require('./documentImport').default,
  );
  app.delete(
    `/tenant/:tenantId/document`,
    require('./documentDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/document/autocomplete`,
    require('./documentAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/document`,
    require('./documentList').default,
  );
  app.get(
    `/tenant/:tenantId/document/:id`,
    require('./documentFind').default,
  );
};
